// <auto-generated />
namespace WebService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class V0103 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V0103));
        
        string IMigrationMetadata.Id
        {
            get { return "201704201423277_V01.03"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
