// <auto-generated />
namespace WebService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class V0102 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V0102));
        
        string IMigrationMetadata.Id
        {
            get { return "201704130703012_V01.02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
